blueprint:
  domain: automation
  name: Easee Load Balancing
  description: This automation adapts the Easee circut limits based on house consumption.
  source_url: https://github.com/dala318/easee_load_balancing/blob/main/easee_load_balancing.yaml
  input:
    ichargerstatus:
      name: Charger status
      description: 'The Easee status (the one ending with _status).'
      selector:
        entity:
          domain: sensor
          multiple: false
    iphase1:
      name: Mains phase 1 current sensor
      description: 'Make sure it is the phase that Easee uses as phase 1'
      selector:
        entity:
          domain: sensor
          device_class: current
          multiple: false
    iphase2:
      name: Mains phase 2 current sensor
      description: 'Make sure it is the phase that Easee uses as phase 2'
      selector:
        entity:
          domain: sensor
          device_class: current
          multiple: false
    iphase3:
      name: Mains phase 3 current sensor
      description: 'Make sure it is the phase that Easee uses as phase 3'
      selector:
        entity:
          domain: sensor
          device_class: current
          multiple: false
    idecreasebelow:
      name: 'Reduce allowed current on phase if total consumption on phase is above'
      description: 'Should be set to main fuse capacity or slightly below.'
      selector:
        number:
          min: 0.0
          max: 40.0
          step: 1.0
          unit_of_measurement: ampere
          mode: slider
      default: 20
    iallowincrease:
      name: 'Allow increasing limit if total consumption on phase is below'
      description: 'Should be set slightly below the max allowed consumption.'
      selector:
        number:
          min: 0.0
          max: 40.0
          step: 1.0
          unit_of_measurement: ampere
          mode: slider
      default: 14
    imaxallowed:
      name: 'Maximum allowed current per phase on charger'
      description: 'Regardless of total consumption the allowed current per phase will not increase beyond this value'
      selector:
        number:
          min: 6.0
          max: 40.0
          step: 1.0
          unit_of_measurement: ampere
          mode: slider
      default: 16
triggers:
  - trigger: state
    entity_id:
      - !input iphase1
      - !input iphase2
      - !input iphase3
conditions:
  - condition: state
    entity_id: !input ichargerstatus
    state: charging
action:
  - service: easee.set_circuit_dynamic_limit
    data:
      charger_id: "{{ state_attr(entChargerStatus,'id') }}"
      current_p1: "{{ valPhase1Limit }}"
      current_p2: "{{ valPhase1Limit }}"
      current_p3: "{{ valPhase1Limit }}"
      time_to_live: 10
variables:
  entChargerStatus: !input ichargerstatus
  valPhase1Limit: >-
    {% set C1 = states("sensor.slimmelezer_current_phase_1") | int() %}
    {% set L1 = state_attr("sensor.ehpsw796_dynamic_circuit_limit", "state_dynamicCircuitCurrentP1") | int() %}
    {% if C1 >= !input reduce_above %}
      {% set change = True %}
      {{ L1 - 1 }}
    {% elif C1 < !input idecreasebelow and L1 < !input imaxallowed %}
      {% set change = True %}
      {{ L1 + 1 }}
    {% endif %}
    {{ L1 }}
mode: single
max_exceeded: silent
