blueprint:
  domain: automation
  name: Easee Load Balancing
  description: This automation adapts the Easee circut limits based on house consumption.
  source_url: https://github.com/dala318/easee_load_balancing/blob/main/easee_load_balancing.yaml
  input:
    ichargerstatus:
      name: Charger status
      description: 'The Easee status (the one ending with _status).'
      selector:
        entity:
          domain: sensor
          multiple: false
    ichargercircuitlimit:
      name: Charger dynamic circuit limit
      description: 'The Easee limit (the one ending with _dynamic_circuit_limit), it may have to be manualy enabled.'
      selector:
        entity:
          domain: sensor
          multiple: false
    iphase1:
      name: Mains phase 1 current sensor
      description: 'Make sure it is the phase that Easee uses as phase 1'
      selector:
        entity:
          domain: sensor
          device_class: current
          multiple: false
    iphase2:
      name: Mains phase 2 current sensor
      description: 'Make sure it is the phase that Easee uses as phase 2'
      selector:
        entity:
          domain: sensor
          device_class: current
          multiple: false
    iphase3:
      name: Mains phase 3 current sensor
      description: 'Make sure it is the phase that Easee uses as phase 3'
      selector:
        entity:
          domain: sensor
          device_class: current
          multiple: false
    idecreaseabove:
      name: 'Reduce allowed current on phase if total consumption on phase is above'
      description: 'Should be set to main fuse capacity or slightly below.'
      selector:
        number:
          min: 0.0
          max: 40.0
          step: 1.0
          unit_of_measurement: ampere
          mode: slider
      default: 20
    iallowincrease:
      name: 'Allow increasing limit if total consumption on phase is below'
      description: 'Should be set slightly below the max allowed consumption.'
      selector:
        number:
          min: 0.0
          max: 40.0
          step: 1.0
          unit_of_measurement: ampere
          mode: slider
      default: 14
    imaxallowed:
      name: 'Maximum allowed current per phase on charger'
      description: 'Regardless of total consumption the allowed current per phase will not increase beyond this value'
      selector:
        number:
          min: 6.0
          max: 40.0
          step: 1.0
          unit_of_measurement: ampere
          mode: slider
      default: 16
triggers:
  - trigger: state
    entity_id:
      - !input iphase1
      - !input iphase2
      - !input iphase3
conditions:
  - condition: state
    entity_id: !input ichargerstatus
    state: charging
  - condition: or
    conditions:
      - condition: numeric_state
        entity_id: !input iphase1
        above: !input idecreaseabove
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: !input iphase1
            below: !input iallowincrease
          - condition: numeric_state
            entity_id: !input ichargercircuitlimit
            attribute: state_dynamicCircuitCurrentP1
            below: !input iallowincrease
      - condition: numeric_state
        entity_id: !input iphase2
        above: !input idecreaseabove
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: !input iphase2
            below: !input iallowincrease
          - condition: numeric_state
            entity_id: !input ichargercircuitlimit
            attribute: state_dynamicCircuitCurrentP2
            below: !input iallowincrease
      - condition: numeric_state
        entity_id: !input iphase3
        above: !input idecreaseabove
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: !input iphase3
            below: !input iallowincrease
          - condition: numeric_state
            entity_id: !input ichargercircuitlimit
            attribute: state_dynamicCircuitCurrentP3
            below: !input iallowincrease
action:
  - service: easee.set_circuit_dynamic_limit
    data:
      charger_id: "{{ state_attr(entChargerStatus,'id') }}"
      current_p1: >-
        {% set C1 = states(entPhase1) | int() %}
        {% set L1 = state_attr(entChargerLimit, "state_dynamicCircuitCurrentP1") %}
        {% if C1 >= valDecreaseAbove %}
          {{ L1 - 1 }}
        {% elif C1 < valAllowIncrease and L1 < valMaxAllowed %}
          {{ L1 + 1 }}
        {% else %}
          {{ L1 }}
        {% endif %}
      current_p2: >-
        {% set C2 = states(entPhase1) | int() %}
        {% set L2 = state_attr(entChargerLimit, "state_dynamicCircuitCurrentP2") %}
        {% if C2 >= valDecreaseAbove %}
          {{ L2 - 1 }}
        {% elif C2 < valAllowIncrease and L2 < valMaxAllowed %}
          {{ L2 + 1 }}
        {% else %}
          {{ L2 }}
        {% endif %}
      current_p3: >-
        {% set C3 = states(entPhase1) | int() %}
        {% set L3 = state_attr(entChargerLimit, "state_dynamicCircuitCurrentP3") %}
        {% if C3 >= valDecreaseAbove %}
          {{ L3 - 1 }}
        {% elif C3 < valAllowIncrease and L3 < valMaxAllowed %}
          {{ L3 + 1 }}
        {% else %}
          {{ L3 }}
        {% endif %}
      time_to_live: 10
variables:
  entChargerStatus: !input ichargerstatus
  entChargerLimit: !input ichargercircuitlimit
  entPhase1: !input iphase1
  entPhase2: !input iphase2
  entPhase3: !input iphase3
  valDecreaseAbove: !input idecreaseabove
  valAllowIncrease: !input iallowincrease
  valMaxAllowed: !input imaxallowed
mode: single
max_exceeded: silent
